

services:

  web:
    build: .
    container_name: greencrescent_web

    ports:
      - "8080:80"

    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: GreenCrescent_Rentals
      DB_PORT: 3306

    depends_on:
      - db

  db:

    image: mysql:8.0

    container_name: greencrescent_db

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: GreenCrescent_Rentals

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d

volumes:

  mysql_data: